name: citra-transifex

on:
  push:
    branches: [ master ]

jobs:
  transifex:
    runs-on: ubuntu-latest
    container: ryzenDew/build-environments:linux-fresh
    if: ${{ github.repository == 'ryzendew/Lime-3DS-Emulator' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Update Translation
        run: ./.ci/transifex.sh
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
